### ISSUE TITLE
Upgrade Protocol to Cairo 1.0

### ISSUE THREAD

**Issue by Bal7hazar** [Carbonable/carbon-protocol#153]
**Description**

Upgrade all contracts to Cairo 1.0

**Cairo 1.0**

Installation guide:
- https://medium.com/@elias.tazartes/ahead-of-the-curve-install-cairo-1-0-alpha-and-prepare-for-regenesis-85f4e3940e20

Starklings
- https://github.com/shramee/starklings-cairo1

**Benchmarks**

- https://github.com/Darlington02/min-starknet/tree/cairo1.0/cairo1.0
- https://github.com/keep-starknet-strange/quaireaux
- https://github.com/OpenZeppelin/cairo-contracts/pull/556/files#diff-934b348f6edf02857bf4a95bc55568cc75b633ba1530ee665ee9fb00db8dc0e8

**Package manager**

- Scarb
  - https://blog.swmansion.com/say-hello-to-scarb-a-cairo-1-0-package-manager-782b0321f82f
  - https://github.com/software-mansion/scarb/discussions/79

**Comment by zeapherine** [comment]
Can I get some tasks for migration? I would like to contribute.

**Comment by Bal7hazar** [comment]
Thanks @zeapherine for your interest, in order to migrate we need first to migrate our dependencies, which are (from few to high workload):

- https://github.com/carbonable-labs/cairo-erc-4906/issues/3
- https://github.com/carbonable-labs/cairo-erc-2981/issues/3
- https://github.com/carbonable-labs/cairo-migrator/issues/5
- https://github.com/carbonable-labs/cairo-erc-3525/issues/28

Feel free to make a PR about the one you are the most interested :pray:

**Comment by cloudvenger** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-Tech-Team-workspace-64527a8c74b9f900123e10f6/issues/Carbonable/carbon-protocol/153?planning-poker) with Zenhub @Bal7hazar
