### ISSUE TITLE
[Fix] Prevent over-minting

### ISSUE THREAD

**Issue by tekkac** [Carbonable/carbon-protocol#213]
**Description**
---
Minting should be capped by projectValue and checked within the Project.
Minter sold_out should be updated if necessary.

**Acceptance Criteria**
---

- [ ] Fix bug
- [ ] Update tests

**Comment by edisontim** [comment]
Can I work on this one if not already closed :) ?

**Comment by tekkac** [comment]
We forgot to close it, sorry
