### ISSUE TITLE
Prerequisites to Protocol v3 - Migrate ERC-1155 contracts to Cairo 1 (v2) & component

### ISSUE THREAD

**Issue by cloudvenger** [Carbonable/carbon-protocol#270]
**Description**
---
As prerequisites to Protocol v3 - implement and [migrate ERC-1155 contracts (to Cairo 1 (v2) & component)](https://github.com/OpenZeppelin/cairo-contracts/issues/572)

**Acceptance Criteria**
---

- [ ] Help on implementation of ERC-1155 (to Cairo 1 (v2) & component) on Openzepplin repo
- [ ]  Add ERC-1155

**Comment by G2CARBZ** [comment]
Arnaud's personal time
