### ISSUE TITLE
Sold Out - las delicias + Banegas Farm

### ISSUE THREAD

**Issue by G2CARBZ** [Carbonable/carbon-protocol#310]
dApp : https://app.carbonable.io/launchpad/forest-regeneration-banegas-farm-costa-rica

* mettre les projets (las delicias et Banegas Farm) soldout 
* Funding 100% 
* Mettre le bon bouton (Claim your sft)

<img width="1132" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNE4rQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--afca2683dee207e4addf660a9038f5028a640d31/image.png" alt="image.png" />

**Comment by Khyati729** [comment]
Clean Out - Transition

**Comment by G2CARBZ** [comment]
@schwepps potneitally need to hardcode it. Let synch with @cloudvenger

**Comment by schwepps** [comment]
@cloudvenger @MartianGreed I think we just need to force is_soldout in the indexer and it will fix everything at once.

**Comment by cloudvenger** [comment]
Agreed

**Comment by MartianGreed** [comment]
Done

**Comment by schwepps** [comment]
Closing as done by @MartianGreed on backend side.
