### ISSUE TITLE
Smart Contract - Transfer ownership improvement

### ISSUE THREAD

**Issue by Bal7hazar** [Carbonable/carbon-protocol#59]
**Description**
---
To secure ownership transfer, we can add a feature to ask the new owner to accept the ownership before processing the transfer.

Feature: [OpenZeppelin!505](https://github.com/OpenZeppelin/cairo-contracts/pull/505)

**Acceptance Criteria**
---

- [ ] Relevant smart contracts adopts the new feature.

**Comment by tekkac** [comment]
not relevant anymore
