### ISSUE TITLE
[Offseter] Implement a function, for an address, to trigger the Offseting of his Carbon Credit

### ISSUE THREAD

**Issue by cloudvenger** [Carbonable/carbon-protocol#84]
**Description**
---
Implement a function, for an address, to trigger the Offseting of his Carbon Credit.

**Questions**
---
- The address need to Offset for each of his project ?
- Can we trigger the Offseting for all the Projects in the same time ?

**Acceptance Criteria**
---
- [ ] Implement unit tests for each functions
- [ ] Implement integration tests for each functions
- [ ] If needed, write the documentation associated with the functions and events exposed

**Additional context**
---
excalidraw - [Farming schema](https://app.excalidraw.com/l/4BTLOTSvKjp/6YHFPM8REmR)

**Comment by Bal7hazar** [comment]
The offset feature must be called for each projects.
We could reconsider it when we will integrate the 3525 format.

**Comment by cloudvenger** [comment]
My thinking:
From the Dapp, we should be able to trigger only one button to offset all `carbon_offsetable` and the Dapp will do multi-call on each project of the caller, by trigger the func `offset`.

**Comment by cloudvenger** [comment]
Maybe we should convert this Issue into Dapp Issue as the func `offset` is ready for each project.

**Comment by Bal7hazar** [comment]
Something that we didn't manage is if the use can offset a part of his offsetable balance, actually with the current version he can only offset all his balance.
Doing a multi call on all projects will make difficult to manage all the spread offsetable amounts.
